# .github/workflows/bluesky_metadata_collection.yml
name: Bluesky Metadata Collection

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual triggering
    inputs:
      input_file:
        description: 'Input file path (relative to repo root)'
        required: false
        default: 'data/usernames.txt'
      output_file:
        description: 'Output file path (relative to repo root)'
        required: false
        default: 'data/metadata.csv'

jobs:
  collect-metadata:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create data directory
      run: mkdir -p data
      
    - name: Run metadata collection
      env:
        BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
        BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
      run: |
        python scripts/collect_bluesky_metadata.py \
          --input_file="${{ github.event.inputs.input_file || 'data/usernames.txt' }}" \
          --output_file="data/metadata_$(date +%Y%m%d_%H%M%S).csv"
          
    - name: Run tests
      run: pytest tests/ -v
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bluesky-metadata-${{ github.run_number }}
        path: |
          data/metadata_*.csv
          logs/*.log
        retention-days: 30
        
    - name: Commit and push results
      if: success()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/metadata_*.csv
        git commit -m "Update Bluesky metadata collection $(date +%Y-%m-%d)" || exit 0
        git push
